### ISSUE TITLE
New feature idea: Switch to next/previous Virtual Desktop 

### ISSUE THREAD

**Issue by kiddvmn** [YourOrdinaryCat/Charmy#11]
Hello. Is it possible to implement this feature? For example: Right corner > switch to next desktop, left corner > switch to previous desktop. Thanks for useful app btw!

**Comment by YourOrdinaryCat** [comment]
Not sure about 86Box, but Task Manager & Hyper-V are actually launching as administrator - the UAC notification won't pop up for them (and some other built in apps/services) by default, you need these UAC settings if you want to see the notification:

![User Account Control Settings, with the slider set to "Always notify"](https://github.com/user-attachments/assets/fb156cbe-c7a6-4d82-ba54-ae1eb5cd12cc)

**Comment by YourOrdinaryCat** [comment]
This will ship on the next release.
